### PR TITLE
Update eqFTP-password.html

### PR DESCRIPTION
**Pull request by Pot-Nut**
Added autofocus to the password field.

### CODE REVIEW

**Comment by Equals182** [comment]
Damn dude! Is it working? I can't check it right now.
I was looking for autofocus but I was too dumb to look at css.
Gonna merge it in 4 hours when I'll get home

**Comment by Pot-Nut** [comment]
It works the first time the password modal is opened, but if you cancel then re-open the modal it stops working. It's still better than nothing!

**Comment by Equals182** [comment]
Oh, alright! Gonna dig a bit more later. 
I'll merge it but it'll be added in v0.7.0 which will come out in the end of month (at least I hope so)

**Comment by Equals182** [comment]
And huge thanks for your contribution! Hope you have no problems working with eqFTP.

**Comment by Pot-Nut** [comment]
No problem! I did also try setting focus in the Javascript (done callback of the open modal function) but this didn't appear to do anything.

The only other issue I seem to have is uploads sitting on 'Waiting' every now and again which requires a restart to Brackets to fix. Probably something to do with my bad wifi connection at work (slow connection, drops frequently, and I have to access through a VPN!) so I wouldn't worry too much about it.

Props on the extension though - I use it every day!

**Pull request merged**
