### PR TITLE
Update string.js

### PR DESCRIPTION
**Pull request by dennyschwender**
Translated all NEW strings to italian

### CODE REVIEW

**Comment by Equals182** [comment]
Thanks dude!

**Comment by dennyschwender** [comment]
Thanks for your work, I was waiting a SFTP plugin from long time.


Il giorno mar 5 mag 2015 alle ore 13:09 Alexander <notifications@github.com>
ha scritto:

**Comment by Equals182** [comment]
You can test it now, just [install beta version](http://equals182.github.io/eqFTP/#installing)

**Comment by dennyschwender** [comment]
I've installed it today, at this moment no problem, it works perfectly.


Il giorno mar 5 mag 2015 alle ore 14:50 Alexander <notifications@github.com>
ha scritto:

**Comment by Equals182** [comment]
Glad to hear it! Have fun, dude :beers:

**Pull request merged**
